// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufdkqigfwyqpwltwxeqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZGtxaWdmd3lxcHdsdHd4ZXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTE4NjgsImV4cCI6MjA1NDk2Nzg2OH0.me5_xNLcLDPs4qSyFEA-ZF5H_ZSe1qa7TDYwV7Q417o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);